"use strict";

const { OFF, WRN, ERR } = require("./levels");
const { removeOffRules } = require("./utils");

const possibleErrors = {
  "for-direction"                : WRN,
  "getter-return"                : ERR,
  "no-async-promise-executor"    : ERR,
  "no-await-in-loop"             : OFF,
  "no-compare-neg-zero"          : ERR,
  "no-cond-assign"               : [WRN, "always"],
  "no-console"                   : WRN,
  "no-constant-condition"        : [WRN, { "checkLoops": false }],
  "no-control-regex"             : OFF,
  "no-debugger"                  : ERR,
  "no-dupe-args"                 : ERR,
  "no-dupe-else-if"              : ERR,
  "no-dupe-keys"                 : ERR,
  "no-duplicate-case"            : ERR,
  "no-empty"                     : ERR,
  "no-empty-character-class"     : ERR,
  "no-ex-assign"                 : ERR,
  "no-extra-boolean-cast"        : [ERR, { "enforceForLogicalOperands": true }],
  "no-extra-parens"              : OFF,
  "no-extra-semi"                : ERR,
  "no-func-assign"               : ERR,
  "no-import-assign"             : ERR,
  "no-inner-declarations"        : ERR,
  "no-invalid-regexp"            : ERR,
  "no-irregular-whitespace"      : ERR,
  "no-loss-of-precision"         : ERR,
  "no-misleading-character-class": ERR,
  "no-obj-calls"                 : ERR,
  "no-promise-executor-return"   : OFF,
  "no-prototype-builtins"        : ERR,
  "no-regex-spaces"              : ERR,
  "no-setter-return"             : ERR,
  "no-sparse-arrays"             : ERR,
  "no-template-curly-in-string"  : WRN,
  "no-unexpected-multiline"      : ERR,
  "no-unreachable"               : ERR,
  "no-unreachable-loop"          : ERR,
  "no-unsafe-finally"            : ERR,
  "no-unsafe-negation"           : [ERR, { "enforceForOrderingRelations": true }],
  "no-useless-backreference"     : ERR,
  "require-atomic-updates"       : WRN,
  "use-isnan"                    : [ERR, {
    "enforceForSwitchCase": true,
    "enforceForIndexOf"   : true,
  }],
  "valid-typeof": ERR,
};

const bestPractices = {
  "accessor-pairs"              : OFF,
  "array-callback-return"       : ERR,
  "block-scoped-var"            : ERR,
  "class-methods-use-this"      : OFF,
  "complexity"                  : OFF,
  "consistent-return"           : ERR,
  "curly"                       : ERR,
  "default-case"                : ERR,
  "default-case-last"           : ERR,
  "default-param-last"          : ERR,
  "dot-location"                : [ERR, "property"],
  "dot-notation"                : OFF,
  "eqeqeq"                      : ERR,
  "grouped-accessor-pairs"      : [ERR, "getBeforeSet"],
  "guard-for-in"                : WRN,
  "max-classes-per-file"        : OFF,
  "no-alert"                    : ERR,
  "no-caller"                   : ERR,
  "no-case-declarations"        : ERR,
  "no-constructor-return"       : ERR,
  "no-div-regex"                : OFF,
  "no-else-return"              : OFF,
  "no-empty-function"           : OFF,
  "no-empty-pattern"            : ERR,
  "no-eq-null"                  : ERR,
  "no-eval"                     : ERR,
  "no-extend-native"            : ERR,
  "no-extra-bind"               : ERR,
  "no-extra-label"              : ERR,
  "no-fallthrough"              : ERR,
  "no-floating-decimal"         : ERR,
  "no-global-assign"            : ERR,
  "no-implicit-coercion"        : [ERR, { "allow": ["!!"] }],
  "no-implicit-globals"         : [ERR, { "lexicalBindings": true }],
  "no-implied-eval"             : ERR,
  "no-invalid-this"             : [WRN, { "capIsConstructor": false }],
  "no-iterator"                 : ERR,
  "no-labels"                   : OFF,
  "no-lone-blocks"              : ERR,
  "no-loop-func"                : ERR,
  "no-magic-numbers"            : OFF,
  "no-multi-spaces"             : OFF,
  "no-multi-str"                : ERR,
  "no-new"                      : ERR,
  "no-new-func"                 : OFF,
  "no-new-wrappers"             : ERR,
  "no-octal"                    : ERR,
  "no-octal-escape"             : OFF,
  "no-param-reassign"           : WRN,
  "no-proto"                    : ERR,
  "no-redeclare"                : ERR,
  "no-restricted-properties"    : OFF,
  "no-return-assign"            : ERR,
  "no-return-await"             : ERR,
  "no-script-url"               : OFF,
  "no-self-assign"              : ERR,
  "no-self-compare"             : ERR,
  "no-sequences"                : ERR,
  "no-throw-literal"            : WRN,
  "no-unmodified-loop-condition": WRN,
  "no-unused-expressions"       : ERR,
  "no-unused-labels"            : ERR,
  "no-useless-call"             : ERR,
  "no-useless-catch"            : ERR,
  "no-useless-concat"           : ERR,
  "no-useless-escape"           : ERR,
  "no-useless-return"           : ERR,
  "no-void"                     : ERR,
  "no-warning-comments"         : WRN,
  "no-with"                     : ERR,
  "prefer-named-capture-group"  : OFF,
  "prefer-promise-reject-errors": WRN,
  "prefer-regex-literals"       : ERR,
  "radix"                       : ERR,
  "require-await"               : WRN,
  "require-unicode-regexp"      : OFF,
  "vars-on-top"                 : ERR,
  "wrap-iife"                   : ERR,
  "yoda"                        : OFF,
};

const strictMode = {
  "strict": ERR,
};

const variables = {
  "init-declarations"         : OFF,
  "no-delete-var"             : ERR,
  "no-label-var"              : ERR,
  "no-restricted-globals"     : OFF,
  "no-shadow"                 : OFF,
  "no-shadow-restricted-names": ERR,
  "no-undef"                  : ERR,
  "no-undef-init"             : OFF,
  "no-undefined"              : OFF,
  "no-unused-vars"            : [ERR, {
    "ignoreRestSiblings": true,
    "argsIgnorePattern" : "^_",
  }],
  "no-use-before-define": [WRN, { "functions": false }],
};

const stylisticIssues = {
  "array-bracket-newline": OFF,
  "array-bracket-spacing": [ERR, "never"],
  "array-element-newline": OFF,
  "block-spacing"        : [ERR, "always"],
  "brace-style"          : [ERR, "1tbs", { "allowSingleLine": true }],
  "camelcase"            : ERR,
  "capitalized-comments" : OFF,
  "comma-dangle"         : [ERR, {
    "arrays"   : "always-multiline",
    "objects"  : "always-multiline",
    "imports"  : "always-multiline",
    "exports"  : "always-multiline",
    "functions": "never",
  }],
  "comma-spacing"                 : [ERR, { "before": false, "after": true }],
  "comma-style"                   : [ERR, "last"],
  "computed-property-spacing"     : [ERR, "never"],
  "consistent-this"               : OFF,
  "eol-last"                      : ERR,
  "func-call-spacing"             : [ERR, "never"],
  "func-name-matching"            : ERR,
  "func-names"                    : OFF,
  "func-style"                    : [ERR, "declaration", { "allowArrowFunctions": true }],
  "function-call-argument-newline": OFF,
  "function-paren-newline"        : OFF,
  "id-denylist"                   : OFF,
  "id-length"                     : OFF,
  "id-match"                      : OFF,
  "implicit-arrow-linebreak"      : OFF,
  "indent"                        : [ERR, 2, {
    "SwitchCase"        : 1,
    "VariableDeclarator": "first",
    "ignoredNodes"      : ["ConditionalExpression"],
  }],
  "jsx-quotes" : [ERR, "prefer-double"],
  "key-spacing": [ERR, {
    "beforeColon": false,
    "afterColon" : true,
    "align"      : "colon",
  }],
  "keyword-spacing"                 : [ERR, { "before": true, "after": true }],
  "line-comment-position"           : OFF,
  "linebreak-style"                 : [ERR, "unix"],
  "lines-around-comment"            : OFF,
  "lines-between-class-members"     : [ERR, "always", { "exceptAfterSingleLine": true }],
  "max-depth"                       : OFF,
  "max-len"                         : [WRN, { "code": 100, "tabWidth": 2 }],
  "max-lines"                       : OFF,
  "max-lines-per-function"          : OFF,
  "max-nested-callbacks"            : OFF,
  "max-params"                      : OFF,
  "max-statements"                  : OFF,
  "max-statements-per-line"         : OFF,
  "multiline-comment-style"         : OFF,
  "multiline-ternary"               : OFF,
  "new-cap"                         : [ERR, { "capIsNewExceptions": ["BigInt"] }],
  "new-parens"                      : ERR,
  "newline-per-chained-call"        : OFF,
  "no-array-constructor"            : ERR,
  "no-bitwise"                      : OFF,
  "no-continue"                     : OFF,
  "no-inline-comments"              : OFF,
  "no-lonely-if"                    : OFF,
  "no-mixed-operators"              : OFF,
  "no-mixed-spaces-and-tabs"        : ERR,
  "no-multi-assign"                 : ERR,
  "no-multiple-empty-lines"         : [ERR, { "max": 2, "maxBOF": 0, "maxEOF": 0 }],
  "no-negated-condition"            : OFF,
  "no-nested-ternary"               : OFF,
  "no-new-object"                   : ERR,
  "no-plusplus"                     : [ERR, { "allowForLoopAfterthoughts": true }],
  "no-restricted-syntax"            : OFF,
  "no-tabs"                         : ERR,
  "no-ternary"                      : OFF,
  "no-trailing-spaces"              : ERR,
  "no-underscore-dangle"            : OFF,
  "no-unneeded-ternary"             : ERR,
  "no-whitespace-before-property"   : ERR,
  "nonblock-statement-body-position": [ERR, "beside"],
  "object-curly-newline"            : OFF,
  "object-curly-spacing"            : [ERR, "always"],
  "object-property-newline"         : OFF,
  "one-var"                         : OFF,
  "one-var-declaration-per-line"    : OFF,
  "operator-assignment"             : OFF,
  "operator-linebreak"              : [ERR, "before", {
    "overrides": {
      "="   : "after",
      "+="  : "after",
      "-="  : "after",
      "*="  : "after",
      "/="  : "after",
      "%="  : "after",
      "**=" : "after",
      "<<=" : "after",
      ">>=" : "after",
      ">>>=": "after",
      "&="  : "after",
      "^="  : "after",
      "|="  : "after",
    },
  }],
  "padded-blocks"                  : [ERR, "never"],
  "padding-line-between-statements": OFF,
  "prefer-exponentiation-operator" : OFF,
  "prefer-object-spread"           : OFF,
  "quote-props"                    : [ERR, "consistent"],
  "quotes"                         : [ERR, "double"],
  "semi"                           : [ERR, "always"],
  "semi-spacing"                   : [ERR, { "before": false, "after": true }],
  "semi-style"                     : [ERR, "last"],
  "sort-keys"                      : OFF,
  "sort-vars"                      : OFF,
  "space-before-blocks"            : [ERR, "always"],
  "space-before-function-paren"    : [ERR, { "anonymous": "always", "named": "never" }],
  "space-in-parens"                : [ERR, "never"],
  "space-infix-ops"                : ERR,
  "space-unary-ops"                : [ERR, { "words": true, "nonwords": false }],
  "spaced-comment"                 : [ERR, "always"],
  "switch-colon-spacing"           : [ERR, { "before": false, "after": true }],
  "template-tag-spacing"           : [ERR, "never"],
  "unicode-bom"                    : [ERR, "never"],
  "wrap-regex"                     : OFF,
};

const ecmaScript6 = {
  "arrow-body-style"      : [ERR, "as-needed"],
  "arrow-parens"          : [ERR, "as-needed"],
  "arrow-spacing"         : [ERR, { "before": true, "after": true }],
  "constructor-super"     : ERR,
  "generator-star-spacing": [ERR, {
    "before": false,
    "after" : true,
    "method": {
      "before": true,
      "after" : false,
    },
  }],
  "no-class-assign"        : ERR,
  "no-confusing-arrow"     : OFF,
  "no-const-assign"        : ERR,
  "no-dupe-class-members"  : ERR,
  "no-duplicate-imports"   : ERR,
  "no-new-symbol"          : ERR,
  "no-restricted-exports"  : OFF,
  "no-restricted-imports"  : OFF,
  "no-this-before-super"   : ERR,
  "no-useless-computed-key": [ERR, { "enforceForClassMembers": true }],
  "no-useless-constructor" : OFF,
  "no-useless-rename"      : ERR,
  "no-var"                 : ERR,
  "object-shorthand"       : [ERR, "methods"],
  "prefer-arrow-callback"  : [ERR, {
    "allowNamedFunctions": true,
    "allowUnboundThis"   : true,
  }],
  "prefer-const"           : ERR,
  "prefer-destructuring"   : OFF,
  "prefer-numeric-literals": ERR,
  "prefer-rest-params"     : ERR,
  "prefer-spread"          : ERR,
  "prefer-template"        : OFF,
  "require-yield"          : WRN,
  "rest-spread-spacing"    : [ERR, "never"],
  "sort-imports"           : OFF,
  "symbol-description"     : OFF,
  "template-curly-spacing" : OFF,
  "yield-star-spacing"     : [ERR, { "before": false, "after": true }],
};

const rules = removeOffRules(
  Object.assign({},
    possibleErrors,
    bestPractices,
    strictMode,
    variables,
    stylisticIssues,
    ecmaScript6
  )
);

module.exports = {
  "rules": rules,
};
